obstacle_range: 10
raytrace_range: 10
footprint: [[0.1, 0.0], [0.0, 0.1], [0.0, -0.1], [-0.1, 0.0]]
#robot_radius: ir_of_robot
inflation_radius: 0.3

observation_sources: laser_scan_sensor

laser_scan_sensor: {sensor_frame: /crawbot1_tf/hokuyo, data_type: LaserScan, topic: /laser/scan, marking: true, clearing: true}
